//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wordle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///and
        ///was
        ///for
        ///with
        ///from
        ///his
        ///that
        ///also
        ///are
        ///which
        ///has
        ///born
        ///its
        ///first
        ///who
        ///new
        ///this
        ///one
        ///were
        ///american
        ///known
        ///district
        ///national
        ///united
        ///she
        ///after
        ///county
        ///their
        ///film
        ///two
        ///been
        ///world
        ///state
        ///states
        ///had
        ///school
        ///but
        ///university
        ///south
        ///football
        ///have
        ///during
        ///album
        ///city
        ///located
        ///may
        ///they
        ///other
        ///season
        ///her
        ///not
        ///family
        ///team
        ///part
        ///played
        ///north
        ///between
        ///most
        ///village
        ///league
        ///series
        ///released
        ///name
        ///all
        ///into
        ///when
        ///species
        ///time
        ///station
        ///member
        ///years
        ///used
        ///area
        ///only
        ///former
        ///second
        ///where
        ///over
        ///won
        ///list
        ///three
        ///music
        ///west
        ///river
        ///since
        ///more
        ///there
        ///war
        ///mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lexipedia_wordlist_3_10 {
            get {
                return ResourceManager.GetString("Lexipedia_wordlist_3_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aaron
        ///ab
        ///abandoned
        ///abc
        ///aberdeen
        ///abilities
        ///ability
        ///able
        ///aboriginal
        ///abortion
        ///about
        ///above
        ///abraham
        ///abroad
        ///abs
        ///absence
        ///absent
        ///absolute
        ///absolutely
        ///absorption
        ///abstract
        ///abstracts
        ///abu
        ///abuse
        ///ac
        ///academic
        ///academics
        ///academy
        ///acc
        ///accent
        ///accept
        ///acceptable
        ///acceptance
        ///accepted
        ///accepting
        ///accepts
        ///access
        ///accessed
        ///accessibility
        ///accessible
        ///accessing
        ///accessories
        ///accessory
        ///accident
        ///accidents
        ///accommodate
        ///accommodation
        ///accommodations
        ///accompanied
        ///accompanying
        ///accomplish
        ///accomplished
        ///accordance
        ///according
        ///accordingly
        ///account
        ///ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MIT_wordlist_10000 {
            get {
                return ResourceManager.GetString("MIT_wordlist_10000", resourceCulture);
            }
        }
    }
}
